import { RawMLBBHubRankedHero, RawProMatchPayload, RawPatchPayload } from '../raw/types';

/**
 * ============================================================================
 * EXPLICIT DEMO / FIXTURE DATA (DEMO_ONLY)
 * ============================================================================
 * WARNING:
 * This data is STRICTLY for testing, offline mock harnesses, and unit tests.
 * Under Phase 2A.5 rules, IT MUST NEVER ENTER THE PRODUCTION DATA PIPELINE
 * or be served as live verified data.
 */

export const DEMO_DATA_FLAG = 'DEMO_ONLY' as const;

export interface DemoWrapped<T> {
  _sourceTag: 'DEMO_ONLY';
  data: T;
}

export const DEMO_RAW_RANKED_DATA: (RawMLBBHubRankedHero & { _sourceTag: 'DEMO_ONLY' })[] = [
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'ling',
    hero_title: 'Ling',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 4210,
    bans_total: 18200,
    wins_total: 2280,
    losses_total: 1930,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/ling',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'fanny',
    hero_title: 'Fanny',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 3120,
    bans_total: 19410,
    wins_total: 1720,
    losses_total: 1400,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/fanny',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'mathilda',
    hero_title: 'Mathilda',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 5120,
    bans_total: 16400,
    wins_total: 2790,
    losses_total: 2330,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/mathilda',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'chou',
    hero_title: 'Chou',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 6200,
    bans_total: 3400,
    wins_total: 3080,
    losses_total: 3120,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/chou',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'suyou',
    hero_title: 'Suyou',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 4800,
    bans_total: 21500,
    wins_total: 2640,
    losses_total: 2160,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/suyou',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'zhuxin',
    hero_title: 'Zhuxin',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 5800,
    bans_total: 17200,
    wins_total: 3120,
    losses_total: 2680,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/zhuxin',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'marcel',
    hero_title: 'Marcel',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 3900,
    bans_total: 8200,
    wins_total: 2020,
    losses_total: 1880,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/marcel',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    hero_key: 'hirara',
    hero_title: 'Hirara',
    patch_ver: '2.2.16',
    tier_bracket: 'MYTHIC_PLUS',
    server_region: 'GLOBAL',
    sample_games: 28450,
    picks_total: 4100,
    bans_total: 12400,
    wins_total: 2190,
    losses_total: 1910,
    date_start: '2026-09-08',
    date_end: '2026-09-20',
    ingested_at: '2026-09-20T10:00:00.000Z',
    origin_url: 'https://mlbbhub.com/api/v1/ranked/heroes/hirara',
  },
];

export const DEMO_RAW_PRO_MATCHES: (any & { _sourceTag: 'DEMO_ONLY' })[] = [
  {
    _sourceTag: 'DEMO_ONLY',
    match_uid: 'MPL-ID-S14-W3-M1-G1',
    league: 'MPL Indonesia Season 14',
    geo_region: 'ID',
    game_patch: '2.2.16',
    team_first: 'Fnatic ONIC',
    team_second: 'RRQ Hoshi',
    winner_team: 'Fnatic ONIC',
    duration_sec: 1140,
    bans_first_pick: ['fanny', 'ling', 'mathilda', 'suyou', 'zhuxin'],
    bans_second_pick: ['chou', 'hirara', 'marcel', 'nolan', 'hayabusa'],
    picks_first_pick: [
      { hero_id: 'ling', player_ign: 'Kairi', position: 'JUNGLE', kills: 7, deaths: 1, assists: 6 },
      { hero_id: 'chou', player_ign: 'Kiboy', position: 'ROAM', kills: 1, deaths: 3, assists: 11 },
      { hero_id: 'zhuxin', player_ign: 'Sanz', position: 'MID', kills: 4, deaths: 2, assists: 9 },
      { hero_id: 'harith', player_ign: 'CW', position: 'GOLD', kills: 5, deaths: 1, assists: 5 },
      { hero_id: 'terizla', player_ign: 'Lutpiii', position: 'EXP', kills: 2, deaths: 2, assists: 8 },
    ],
    picks_second_pick: [
      { hero_id: 'suyou', player_ign: 'Sutsujin', position: 'JUNGLE', kills: 4, deaths: 4, assists: 3 },
      { hero_id: 'mathilda', player_ign: 'Idok', position: 'ROAM', kills: 0, deaths: 5, assists: 6 },
      { hero_id: 'valentina', player_ign: 'Rinz', position: 'MID', kills: 2, deaths: 3, assists: 4 },
      { hero_id: 'moskov', player_ign: 'Skylar', position: 'GOLD', kills: 2, deaths: 3, assists: 2 },
      { hero_id: 'edith', player_ign: 'Dyrennn', position: 'EXP', kills: 1, deaths: 4, assists: 3 },
    ],
    played_at: '2026-09-12T15:30:00.000Z',
    data_source: 'MLBBHub MPL Indonesia Official Telemetry',
  },
  {
    _sourceTag: 'DEMO_ONLY',
    match_uid: 'MPL-ID-S14-W3-M1-G2',
    league: 'MPL Indonesia Season 14',
    geo_region: 'ID',
    game_patch: '2.2.16',
    team_first: 'RRQ Hoshi',
    team_second: 'Fnatic ONIC',
    winner_team: 'RRQ Hoshi',
    duration_sec: 1260,
    bans_first_pick: ['ling', 'fanny', 'suyou', 'mathilda', 'zhuxin'],
    bans_second_pick: ['chou', 'harith', 'hirara', 'terizla', 'marcel'],
    picks_first_pick: [
      { hero_id: 'hayabusa', player_ign: 'Sutsujin', position: 'JUNGLE', kills: 8, deaths: 1, assists: 4 },
      { hero_id: 'tigreal', player_ign: 'Idok', position: 'ROAM', kills: 1, deaths: 2, assists: 10 },
      { hero_id: 'zhuxin', player_ign: 'Rinz', position: 'MID', kills: 3, deaths: 1, assists: 9 },
      { hero_id: 'claude', player_ign: 'Skylar', position: 'GOLD', kills: 5, deaths: 0, assists: 6 },
      { hero_id: 'ruby', player_ign: 'Dyrennn', position: 'EXP', kills: 2, deaths: 2, assists: 7 },
    ],
    picks_second_pick: [
      { hero_id: 'nolan', player_ign: 'Kairi', position: 'JUNGLE', kills: 3, deaths: 4, assists: 2 },
      { hero_id: 'mathilda', player_ign: 'Kiboy', position: 'ROAM', kills: 0, deaths: 4, assists: 4 },
      { hero_id: 'yve', player_ign: 'Sanz', position: 'MID', kills: 1, deaths: 3, assists: 3 },
      { hero_id: 'bruno', player_ign: 'CW', position: 'GOLD', kills: 2, deaths: 4, assists: 1 },
      { hero_id: 'uranus', player_ign: 'Lutpiii', position: 'EXP', kills: 0, deaths: 4, assists: 2 },
    ],
    played_at: '2026-09-12T16:45:00.000Z',
    data_source: 'MLBBHub MPL Indonesia Official Telemetry',
  },
];

export const DEMO_RAW_PATCH_DATA: any & { _sourceTag: 'DEMO_ONLY' } = {
  _sourceTag: 'DEMO_ONLY',
  patch_id: 'PATCH_2_2_16',
  patch_name: 'Original Server 2.2.16',
  live_date: '2026-09-08',
  season_num: '42',
  server: 'Original Server',
  hero_adjustments: [
    {
      hero_id: 'ling',
      hero_name: 'Ling',
      change_type: 'ADJUST',
      skill_target: 'Skill 1 & Passive',
      summary: 'Energy regeneration adjusted, base critical damage slightly scaled.',
      stat_changes: { 'energy_regen': '+10%', 'crit_rate': '-5%' },
    },
    {
      hero_id: 'fanny',
      hero_name: 'Fanny',
      change_type: 'NERF',
      skill_target: 'Skill 2 Steel Cable',
      summary: 'Energy cost per cable increased slightly in early game.',
      stat_changes: { 'energy_cost_s2': '+2' },
    },
    {
      hero_id: 'mathilda',
      hero_name: 'Mathilda',
      change_type: 'BUFF',
      skill_target: 'Skill 2 Guiding Wind',
      summary: 'Shield capacity granted to allies increased by 15%.',
      stat_changes: { 'shield_base': '+15%' },
    },
  ],
};
